---
# Enable IP forwarding for WiFi passthrough
- name: Enable IPv4 forwarding
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    state: present
    reload: yes

- name: Configure network forwarding in sysctl
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-network-forward.conf
    content: |
      net.ipv4.ip_forward=1
      net.ipv4.conf.all.forwarding=1
    mode: '0644'
  notify: reload sysctl